# Generated by Django 2.1.1 on 2018-10-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytest', '0003_dailyrecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
